apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/rfinland/devspace-vcluster-argocd-demo
    targetRevision: HEAD
    kustomize:
      images:
      - rfinland/devops-toolkit:88775bc59a9b036f1365c66c7acd55434947b0b4
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
